AWSTemplateFormatVersion: "2010-09-09"
Resources:
    DRVPC:
        Type: "AWS::EC2::VPC"
        Properties:
            CidrBlock: "172.31.0.0/16"
            EnableDnsSupport: "true"
            EnableDnsHostnames: "true"
            Tags:
                - Key: Name
                  Value: DRVPC
            InstanceTenancy: default

    PublicSubnetA:
        Type: "AWS::EC2::Subnet"
        Properties:
            CidrBlock: "172.31.0.0/26"
            VpcId: !Ref DRVPC
            AvailabilityZone: "ap-northeast-2a"
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: PublicSubnetA

    PrivateSubnetA:
        Type: "AWS::EC2::Subnet"
        Properties:
            CidrBlock: "172.31.64.0/26"
            VpcId: !Ref DRVPC
            AvailabilityZone: "ap-northeast-2a"
            MapPublicIpOnLaunch: false
            Tags:
                - Key: Name
                  Value: PrivateSubnetA

    PrivateSubnetTRGW:
        Type: "AWS::EC2::Subnet"
        Properties:
            CidrBlock: "172.31.128.0/26"
            VpcId: !Ref DRVPC
            AvailabilityZone: "ap-northeast-2a"
            MapPublicIpOnLaunch: false
            Tags:
                - Key: Name
                  Value: PrivateSubnetTRGW

    WebServer:
        Type: "AWS::EC2::Instance"
        Properties:
            InstanceType: "c5.large"
            ImageId: !Ref "AmazonLinux2023"
            SubnetId: !Ref "PublicSubnetA"
            UserData:
                Fn::Base64: |
                    #!/bin/bash
                    sudo yum update -y
                    sudo amazon-linux-extras install nginx1
                    sudo yum install -y git
                    git clone https://github.com/simjh0919/DRWeb-AWS.git /home/ec2-user/web
                    /home/ec2-user/web/start.sh ${WASServer.PrivateIpAddress}
            Tags:
                - Key: Name
                  Value: WebServer

    SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Allow traffic"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 80
                  ToPort: 80
                  CidrIp: "0.0.0.0/0"
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: "0.0.0.0/0"
            VpcId: !Ref DRVPC

    AmazonLinux2023:
        Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
        Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
