AWSTemplateFormatVersion: "2010-09-09"
Resources:
    SeoulS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub "${AWS::AccountId}-crrlab-ap-northeast-2"
            VersioningConfiguration:
                Status: Enabled
    S3ReplicationRoleSeoul:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub "${AWS::AccountId}-S3-Replication-Role-ap-northeast-2"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: s3.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: S3FullAccessPolicy
                  PolicyDocument:
                      Version: "2012-10-17"
                      Statement:
                          - Effect: Allow
                            Action: "s3:*"
                            Resource: "*"

    S3KMSKeySeoul:
        Type: AWS::KMS::Key
        Properties:
            Description: "KMS key for S3 buckets in Seoul"
            KeyPolicy:
                Version: "2012-10-17"
                Id: key-default-1
                Statement:
                    - Effect: Allow
                      Principal:
                          AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
                      Action: "kms:*"
                      Resource: "*"
                    - Effect: Allow
                      Principal:
                          AWS: !GetAtt S3ReplicationRoleSeoul.Arn
                      Action:
                          - "kms:Encrypt"
                          - "kms:Decrypt"
                          - "kms:ReEncrypt*"
                          - "kms:GenerateDataKey*"
                          - "kms:DescribeKey"
                      Resource: "*"
